import {Course, Teacher, School, Semester, Offered} from './course';

export var TEACHERS: Teacher[] = [
    {"name": "Eric Clapton"},
    {"name": "Jimi Hendrix"},
    {"name": "Joe Perry"},
];

export var SCHOOLS: School[] = [
    {"name": "College of Math"},
    {"name": "College of English"},
    {"name": "College of Information Technology"},
];

export var SEMESTERS: Semester[] = [
    {"description": "2016 Summer"},
    {"description": "2016 Fall"},
    {"description": "2017 Spring"},
    {"description": "2017 Summer"},
    {"description": "2017 Fall"},
];

export var COURSES: Course[] = [
    {"id": 0,
    "title": "Math 101",
    "teacher": TEACHERS[0],
    "school": SCHOOLS[0],
    "degree": true,
    "offered": {"time": 10, "days": ['m','w','f']},
    "prereq": [],
    "enrolled": false,
    "available": false,
    "semesters": [SEMESTERS[2], SEMESTERS[4]],
    "grade": "A-"},
    {"id": 1,
    "title": "Math 102",
    "teacher": TEACHERS[0],
    "school": SCHOOLS[0],
    "degree": false,
    "offered": {"time": 10, "days": ['m','w','f']},
    "prereq": [0],
    "enrolled": false,
    "available": true,
    "semesters": [SEMESTERS[0], SEMESTERS[2]],
    "grade": ""},
    {"id": 2,
    "title": "Math 103",
    "teacher": TEACHERS[0],
    "school": SCHOOLS[0],
    "degree": true,
    "offered": {"time": 10, "days": ['m','w','f']},
    "prereq": [0,1],
    "enrolled": false,
    "available": false,
    "semesters": [SEMESTERS[1], SEMESTERS[3]],
    "grade": ""},

    {"id": 3,
    "title": "English 101",
    "teacher": TEACHERS[1],
    "school": SCHOOLS[1],
    "degree": true,
    "offered": {"time": 10, "days": ['tu','th']},
    "prereq": [],
    "enrolled": false,
    "available": false,
    "semesters": [SEMESTERS[2], SEMESTERS[4]],
    "grade": "B+"},
    {"id": 4,
    "title": "English 102",
    "teacher": TEACHERS[1],
    "school": SCHOOLS[1],
    "degree": false,
    "offered": {"time": 10, "days": ['tu','th']},
    "prereq": [3],
    "enrolled": false,
    "available": true,
    "semesters": [SEMESTERS[0], SEMESTERS[2]],
    "grade": ""},
    {"id": 5,
    "title": "English 103",
    "teacher": TEACHERS[1],
    "school": SCHOOLS[1],
    "degree": false,
    "offered": {"time": 10, "days": ['tu','th']},
    "prereq": [3,4],
    "enrolled": false,
    "available": false,
    "semesters": [SEMESTERS[1], SEMESTERS[3]],
    "grade": ""},

    {"id": 6,
    "title": "Human Computer Interaction 101",
    "teacher": TEACHERS[2],
    "school": SCHOOLS[2],
    "degree": true,
    "offered": {"time": 14, "days": ['m','w','f']},
    "prereq": [],
    "enrolled": false,
    "available": true,
    "semesters": [SEMESTERS[0], SEMESTERS[2]],
    "grade": ""},
    {"id": 7,
    "title": "Human Computer Interaction 102",
    "teacher": TEACHERS[2],
    "school": SCHOOLS[2],
    "degree": true,
    "offered": {"time": 14, "days": ['m','w','f']},
    "prereq": [6],
    "enrolled": false,
    "available": false,
    "semesters": [SEMESTERS[1], SEMESTERS[3]],
    "grade": ""},
    {"id": 8,
    "title": "Human Computer Interaction 103",
    "teacher": TEACHERS[2],
    "school": SCHOOLS[2],
    "degree": false,
    "offered": {"time": 14, "days": ['m','w','f']},
    "prereq": [6,7],
    "enrolled": false,
    "available": false,
    "semesters": [SEMESTERS[2], SEMESTERS[4]],
    "grade": ""},
];
